repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: ^tests
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        verbose: true
        args: [--show-error-codes]
        additional_dependencies: ['types-requests']
        exclude: ^tests
        stages: [pre-push]


  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["--cov=reddit_api", "--cov-report=html"]
        stages: [commit]
        
