name: Python Checks

on:
  push:

jobs:
  lint-mypy-pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy pytest

      - name: Run Flake8
        run: flake8

      - name: Run MyPy
        run: mypy .

      - name: Run Pytest
        run: pytest
