name: Python Checks

on:
  push:
    branches: ['main']

  pull_request:
    branches: ['main']

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Install dependencies
        run: pdm install 

      - name: Run Flake8
        run: flake8 

      - name: Run MyPy
        run: mypy .

      - name: Run pytest
        run: pytest
